/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OrderPlacingAndManifesting;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author anujc
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl1 = new javax.swing.JLabel();
        AddUserBtn = new javax.swing.JButton();
        CreateOrderBtn = new javax.swing.JButton();
        CancelOrderBtn = new javax.swing.JButton();
        ViewManifestBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        Lbl2 = new javax.swing.JLabel();
        AddProductsBtn = new javax.swing.JButton();
        ChkBtn = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OCM");
        setLocation(new java.awt.Point(300, 100));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        Lbl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Lbl1.setText("WELCOME");

        AddUserBtn.setText("Add Users");
        AddUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserBtnMouseClicked(evt);
            }
        });

        CreateOrderBtn.setText("Create an Order");
        CreateOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateOrderBtnMouseClicked(evt);
            }
        });
        CreateOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateOrderBtnActionPerformed(evt);
            }
        });

        CancelOrderBtn.setText("Cancel an Order");
        CancelOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelOrderBtnMouseClicked(evt);
            }
        });

        ViewManifestBtn.setText("View Manifest");
        ViewManifestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewManifestBtnMouseClicked(evt);
            }
        });
        ViewManifestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewManifestBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        Lbl2.setText("Order Creating and Manifesting");

        AddProductsBtn.setText("Add Products");
        AddProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductsBtnActionPerformed(evt);
            }
        });

        ChkBtn.setText("Check Database Connection");
        ChkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ChkBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreateOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewManifestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddProductsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateOrderBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelOrderBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewManifestBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(ChkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserBtnMouseClicked
        new RegisterUserView();
        dispose();
    }//GEN-LAST:event_AddUserBtnMouseClicked

    private void ViewManifestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewManifestBtnActionPerformed
        new ViewManifestView();
        dispose();
    }//GEN-LAST:event_ViewManifestBtnActionPerformed

    private void CreateOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateOrderBtnActionPerformed
        new CreateOrderView1();
        dispose();
    }//GEN-LAST:event_CreateOrderBtnActionPerformed

    private void CreateOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateOrderBtnMouseClicked
        new CreateOrderView1();
        dispose();
    }//GEN-LAST:event_CreateOrderBtnMouseClicked

    private void CancelOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelOrderBtnMouseClicked
        
        new CancelOrderView();   
        dispose();
    }//GEN-LAST:event_CancelOrderBtnMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String S = "Order Creating and Manifesting. A DBMS Project Created By :\nAnuj Chandra\nArchana Chokhani\nAbhijit Prakash\nAbhishek Raj" ;   
        JOptionPane.showMessageDialog(this,S); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new LoginView();
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ViewManifestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewManifestBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewManifestBtnMouseClicked

    private void AddProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductsBtnActionPerformed
        new AddProductsView();
        dispose();
    }//GEN-LAST:event_AddProductsBtnActionPerformed

    private void ChkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkBtnActionPerformed
        String ss = "Connection Established", ff = "Connection Failed.";
        System.out.println("-------- Oracle JDBC Connection Testing ------");
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (ClassNotFoundException e) {
            System.out.println("Driver Undetected. Install JDBC Driver.");
            e.printStackTrace();
            return;
        }
        System.out.println("Oracle JDBC Driver Registered!");
        Connection connection = null;
        try {
            connection = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "is020",
                    "is020");
        } catch (SQLException e) {
            System.out.println("Connection Failed!");
            e.printStackTrace();
            return;
        }
        if (connection != null) {
            ChkBtn.setText(ss);
        } else {
            ChkBtn.setText(ff);
        }
    
    }//GEN-LAST:event_ChkBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
      new LoginView();
      dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductsBtn;
    private javax.swing.JButton AddUserBtn;
    private javax.swing.JButton CancelOrderBtn;
    private javax.swing.JToggleButton ChkBtn;
    private javax.swing.JButton CreateOrderBtn;
    private javax.swing.JLabel Lbl1;
    private javax.swing.JLabel Lbl2;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton ViewManifestBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
