/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OrderPlacingAndManifesting;

import java.sql.SQLException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Anuj Chandra
 */
public class ViewManifestView extends javax.swing.JFrame {

    /**
     * Creates new form ViewManifestView
     */
    public ViewManifestView() {
        initComponents();
        setVisible(true);
        try{
            PopulateComboBox();
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl2 = new javax.swing.JLabel();
        OrderNumberCBox = new javax.swing.JComboBox();
        GoBtn = new javax.swing.JButton();
        Lbl1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Lbl3 = new javax.swing.JLabel();
        Lbl4 = new javax.swing.JLabel();
        Lbl5 = new javax.swing.JLabel();
        Lbl6 = new javax.swing.JLabel();
        Lbl7 = new javax.swing.JLabel();
        Lbl8 = new javax.swing.JLabel();
        Lbl9 = new javax.swing.JLabel();
        Lbl10 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        MobileNumberTF = new javax.swing.JTextField();
        AddressTF = new javax.swing.JTextField();
        PickupCityTF = new javax.swing.JTextField();
        DestinationCityTF = new javax.swing.JTextField();
        ProductIDTF = new javax.swing.JTextField();
        ProductNameTF = new javax.swing.JTextField();
        ProductPriceTF = new javax.swing.JTextField();
        ReturnBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OCM");
        setLocation(new java.awt.Point(300, 50));
        setMinimumSize(null);
        setPreferredSize(null);

        Lbl2.setText("Order Number");

        OrderNumberCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderNumberCBoxActionPerformed(evt);
            }
        });

        GoBtn.setText("GO");
        GoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBtnActionPerformed(evt);
            }
        });

        Lbl1.setText("Select Order Number : ");

        Lbl3.setText("Name");

        Lbl4.setText("Mobile Number");

        Lbl5.setText("Address");

        Lbl6.setText("Pickup City");

        Lbl7.setText("Destination City");

        Lbl8.setText("Product ID");

        Lbl9.setText("Product Name");

        Lbl10.setText("Product Price");

        NameTF.setEditable(false);

        MobileNumberTF.setEditable(false);

        AddressTF.setEditable(false);

        PickupCityTF.setEditable(false);

        DestinationCityTF.setEditable(false);

        ProductIDTF.setEditable(false);

        ProductNameTF.setEditable(false);

        ProductPriceTF.setEditable(false);

        ReturnBtn.setText("Return");
        ReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Return To Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit Program");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl3)
                                .addGap(18, 18, 18)
                                .addComponent(NameTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl4)
                                .addGap(18, 18, 18)
                                .addComponent(MobileNumberTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl5)
                                .addGap(18, 18, 18)
                                .addComponent(AddressTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl6)
                                .addGap(18, 18, 18)
                                .addComponent(PickupCityTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl7)
                                .addGap(18, 18, 18)
                                .addComponent(DestinationCityTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl8)
                                .addGap(18, 18, 18)
                                .addComponent(ProductIDTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl9)
                                .addGap(18, 18, 18)
                                .addComponent(ProductNameTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl10)
                                .addGap(18, 18, 18)
                                .addComponent(ProductPriceTF)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl2)
                                .addGap(18, 18, 18)
                                .addComponent(OrderNumberCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ReturnBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl2)
                    .addComponent(OrderNumberCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl3)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl4)
                    .addComponent(MobileNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl5)
                    .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl6)
                    .addComponent(PickupCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl7)
                    .addComponent(DestinationCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl8)
                    .addComponent(ProductIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl9)
                    .addComponent(ProductNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl10)
                    .addComponent(ProductPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ReturnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnActionPerformed
        dispose();
        new MainView();
    }//GEN-LAST:event_ReturnBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
        new MainView();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void OrderNumberCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderNumberCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderNumberCBoxActionPerformed

    private void GoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBtnActionPerformed
    try{
            String s = OrderNumberCBox.getSelectedItem().toString();
            PopulateFields(s);
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_GoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTF;
    private javax.swing.JTextField DestinationCityTF;
    private javax.swing.JButton GoBtn;
    private javax.swing.JLabel Lbl1;
    private javax.swing.JLabel Lbl10;
    private javax.swing.JLabel Lbl2;
    private javax.swing.JLabel Lbl3;
    private javax.swing.JLabel Lbl4;
    private javax.swing.JLabel Lbl5;
    private javax.swing.JLabel Lbl6;
    private javax.swing.JLabel Lbl7;
    private javax.swing.JLabel Lbl8;
    private javax.swing.JLabel Lbl9;
    private javax.swing.JTextField MobileNumberTF;
    private javax.swing.JTextField NameTF;
    private javax.swing.JComboBox OrderNumberCBox;
    private javax.swing.JTextField PickupCityTF;
    private javax.swing.JTextField ProductIDTF;
    private javax.swing.JTextField ProductNameTF;
    private javax.swing.JTextField ProductPriceTF;
    private javax.swing.JButton ReturnBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    private static final String DB_DRIVER = "oracle.jdbc.driver.OracleDriver";
    private static final String DB_CONNECTION = "jdbc:oracle:thin:@localhost:1521:xe";
    private static final String DB_USER = "is020";
    private static final String DB_PASSWORD = "is020";
    private void PopulateComboBox() throws SQLException{
        Connection dbConnection = null;
        Statement statement = null;
        String selectTableSQL = "select order_id from consignment";
        try {
            dbConnection = getDBConnection();
            System.out.println("Connection Successful. Populating Combo Box.");
            statement = dbConnection.createStatement();
            System.out.println(selectTableSQL);
            ResultSet rs = statement.executeQuery(selectTableSQL);
            while (rs.next()) {
                OrderNumberCBox.addItem(rs.getString(1));
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            if (statement != null) {
                statement.close();
            }
            if (dbConnection != null) {
                dbConnection.close();
            }
        }
    }
    private void PopulateFields(String SelectedItem) throws SQLException{
        System.out.println("Order Number Selected Is : " + SelectedItem);
        Connection dbConnection = null;
        Statement statement = null;
        String selectTableSQL = "select * from consignment where order_id = '" + SelectedItem + "'";
        String s1="",s2="",s3="",s4="",s5="",s6="",s7="",s8="";
        try {
            dbConnection = getDBConnection();
            System.out.println("Connection Successful. Attempting To Populate Fields.");
            statement = dbConnection.createStatement();
            System.out.println(selectTableSQL);
            ResultSet rs = statement.executeQuery(selectTableSQL);
            while (rs.next()) {
                s1= rs.getString(2)+" "+rs.getString(3);
                s2 = rs.getString(4);
                s3 = rs.getString(5);
                s4 = rs.getString(6);
                s5 = rs.getString(7);
                s6 = rs.getString(9);
                s7 = rs.getString(8);
                s8 = rs.getString(10);
                System.out.println("Name : " + s1);
                System.out.println("Mobile Number : " + s2);
                System.out.println("Address : " + s3);
                System.out.println("Pickup City : " + s4);
                System.out.println("Destination City : " + s5);
                System.out.println("Product ID : " + s6);
                System.out.println("Product Name : " + s8);
                System.out.println("Product Price : " + s7);
            }
            NameTF.setText(s1);
            MobileNumberTF.setText(s2);
            AddressTF.setText(s3);
            PickupCityTF.setText(s4);
            DestinationCityTF.setText(s5);
            ProductIDTF.setText(s6);
            ProductNameTF.setText(s8);
            ProductPriceTF.setText(s7);
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            if (statement != null) {
                statement.close();
            }
            if (dbConnection != null) {
                dbConnection.close();
            }
        }
    }
    private static Connection getDBConnection() {
        Connection dbConnection = null;
        try {
            Class.forName(DB_DRIVER);
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        try {
            dbConnection = DriverManager.getConnection(DB_CONNECTION, DB_USER,
                    DB_PASSWORD);
            return dbConnection;
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return dbConnection;
    }

    
}
